////////////////////////////////////////////////////////////////////////////
//
//  This file is part of RTIMULib
//
//  Copyright (c) 2014-2015, richards-tech, LLC
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy of
//  this software and associated documentation files (the "Software"), to deal in
//  the Software without restriction, including without limitation the rights to use,
//  copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the
//  Software, and to permit persons to whom the Software is furnished to do so,
//  subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
//  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
//  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
//  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


#include "RTIMULib.h"
#include "RTMath.h"
#include <stdbool.h>
#include <stdio.h>
#include "Libraries/Adafruit_VL6180x.h"
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include "Libraries/rs232.h"
#include <wiringPi.h>
#include <mcp23017.h>
#include <lcd.h>
#include <softPwm.h>
#include "SensorLib2.h"

#define BUF_SIZE 8
void waitOnTOF(Adafruit_VL6180X);
void waitOnImuYaw(RTIMU *,double);


int main()
{
    SRANGE *srange = initVL6180XwoMUX();

    RTIMU *imu = imuInit();



    //Robot test begin
    int display, j;
    wiringPiSetup();
    mcp23017Setup (100, 0x20);
    for (j=0;j<16;j++)
	pinMode(100+j,OUTPUT);
    digitalWrite(101,0);
    display=lcdInit(2,16,4,100,102,103,104,105,106,0,0,0,0);
    lcdHome(display);
    lcdClear(display);
    lcdPosition(display,0,0);
    pinMode(0, OUTPUT);
    pinMode(2, OUTPUT);
    pinMode(3, OUTPUT);
    softPwmCreate(3, 50, 100);
    softPwmCreate(2, 50, 100);
    softPwmCreate(0, 50, 100);
    softPwmWrite(3,100);
    softPwmWrite(2,0);
    softPwmWrite(0,0);

    int cport_nr=24;
    int bdrate=9600;
  char mode[]={'8','N','1',0}; // 8 data bits, no parity, 1 stop bit

  unsigned char str_send[BUF_SIZE];
  str_send[0] = 0;
  str_send[1] = 30;
  
  if(RS232_OpenComport(cport_nr, bdrate, mode))
  {
    printf("Can not open comport\n");
    return(0);
  }

  usleep(2000000);  /* waits 2000ms for stable condition */
  
  while(1)
  {

    //Go fwd
    usleep(1000000);  /* sleep for 1 Second */
    str_send[0]=1;
    RS232_SendByte(cport_nr,str_send[0]);
    RS232_SendByte(cport_nr,str_send[1]);
	printf("Sent to Arduino: '%3d %3d'\n", str_send[0],str_send[1]);
        lcdPosition(display,0,0);
        lcdPrintf(display,"Sent: '%3d %3d'", str_send[0],str_send[1]);
    waitOnTOF(srange->vl);
    
    //stop
    str_send[0]=0;
    RS232_SendByte(cport_nr,str_send[0]);
    RS232_SendByte(cport_nr,str_send[1]);
	printf("Sent to Arduino: '%3d %3d'\n", str_send[0],str_send[1]);
        lcdPosition(display,0,0);
        lcdPrintf(display,"Sent: '%3d %3d'", str_send[0],str_send[1]);
    double currYaw=getCurrImuYaw(imu);
    usleep(1000000);  /* sleep for 1 Second */


    //Turn Right
    str_send[0]=5;
    RS232_SendByte(cport_nr,str_send[0]);
    RS232_SendByte(cport_nr,str_send[1]);
	printf("Sent to Arduino: '%3d %3d'\n", str_send[0],str_send[1]);
        lcdPosition(display,0,0);
        lcdPrintf(display,"Sent: '%3d %3d'", str_send[0],str_send[1]);
    waitOnImuYaw(imu,currYaw);
    
    //stop
    str_send[0]=0;
    RS232_SendByte(cport_nr,str_send[0]);
    RS232_SendByte(cport_nr,str_send[1]);
	printf("Sent to Arduino: '%3d %3d'\n", str_send[0],str_send[1]);
        lcdPosition(display,0,0);
        lcdPrintf(display,"Sent: '%3d %3d'", str_send[0],str_send[1]);
    currYaw=getCurrImuYaw(imu);
    usleep(1000000);  /* sleep for 1 Second */
  }


  return(0);
}

void waitOnTOF(Adafruit_VL6180X *vl) {
    uint8_t throwaway = vl->readRange();
    delay(100);
    uint8_t range = vl->readRange();
    delay(100);
    while (1) {
	    printf("%d\n",range);
	    if (range <= 100)
		break;
            delay(100);
            range = vl->readRange();
    }
}



RTIMU *imuInit() {
    //  Using RTIMULib here allows it to use the .ini file generated by RTIMULibDemo.
    //  Or, you can create the .ini in some other directory by using:
    //      RTIMUSettings *settings = new RTIMUSettings("<directory path>", "RTIMULib");
    //  where <directory path> is the path to where the .ini file is to be loaded/saved


    RTIMUSettings *settings = new RTIMUSettings("RTIMULib");

    RTIMU *imu = RTIMU::createIMU(settings);

    if ((imu == NULL) || (imu->IMUType() == RTIMU_TYPE_NULL)) {
        printf("No IMU found\n");
        exit(1);
    }

    //  This is an opportunity to manually override any settings before the call IMUInit

    //  set up IMU

    imu->IMUInit();

    //  this is a convenient place to change fusion parameters

    imu->setSlerpPower(0.02);
    imu->setGyroEnable(true);
    imu->setAccelEnable(true);
    imu->setCompassEnable(false);
    return imu;
}

double getCurrImu(RTIMU *imu) {
    RTIMU_DATA imuData = imu->getIMUData();
    RTVector3 vec=imuData.fusionPose;
    double yaw=vec.z() * RTMATH_RAD_TO_DEGREE; 
    printf("current:%f  ",yaw);
    return yaw;
}


void waitOnImu(RTIMU *imu, double start) {
    static double beginValue = getCurrImuYaw(imu);
    static int i = 0; 
    double endAt = 0;
    if((i % 4) == 0){

        endAt = beginValue;
    }    
    else if((i % 4) == 1){

        endAt = beginValue + 90.0;
    }
    else if((i % 4) == 2){

        endAt = beginValue + 180.0;
    }
    else if((i % 4) == 3){

        endAt = beginValue + 270.0;
    }
    endAt = fmod(endAt,360.0);
    double currYaw= 0.0f;  
    usleep(imu->IMUGetPollInterval()*1000);
    while (1) { 
    while (imu->IMURead()) {
	currYaw=getCurrImuYaw(imu);
        printf("target:  %f\n",endAt);
    	if (currYaw >= endAt  && currYaw <= endAt+10)
	    break;
        delay(100);
    }
    	if (currYaw >= endAt  && currYaw <= endAt+10)
	    break;
    }
    i = i +1;
}
    
    

